"""Auto migration

Revision ID: 06ffc6d4c520
Revises:
Create Date: 2026-01-14 22:15:38.440472

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06ffc6d4c520"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS rbac;")
    op.execute("CREATE SCHEMA IF NOT EXISTS users;")
    op.create_table(
        "permissions",
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Full permission string (e.g., 'users:delete')",
        ),
        sa.Column(
            "resource",
            sa.String(length=50),
            nullable=False,
            comment="Resource this permission applies to (e.g., 'users')",
        ),
        sa.Column(
            "action",
            sa.String(length=50),
            nullable=False,
            comment="Action allowed on the resource (e.g., 'delete')",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Human-readable description of this permission",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the record",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this record was last updated",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            comment="Soft delete flag. True means record is logically deleted",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="rbac",
    )
    with op.batch_alter_table("permissions", schema="rbac") as batch_op:
        batch_op.create_index(
            "ix_permissions_resource_action", ["resource", "action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_rbac_permissions_is_deleted"), ["is_deleted"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_rbac_permissions_name"), ["name"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_rbac_permissions_resource"), ["resource"], unique=False
        )

    op.create_table(
        "roles",
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=False,
            comment="Unique role identifier (lowercase, e.g., 'admin')",
        ),
        sa.Column(
            "display_name",
            sa.String(length=100),
            nullable=False,
            comment="Human-friendly display name (e.g., 'Administrator')",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Description of this role and its purpose",
        ),
        sa.Column(
            "is_system_role",
            sa.Boolean(),
            nullable=False,
            comment="If True, this role cannot be deleted (protected)",
        ),
        sa.Column(
            "parent_role_id",
            sa.Integer(),
            nullable=True,
            comment="Parent role ID for permission inheritance",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the record",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this record was last updated",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            comment="Soft delete flag. True means record is logically deleted",
        ),
        sa.ForeignKeyConstraint(
            ["parent_role_id"],
            ["rbac.roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="rbac",
    )
    with op.batch_alter_table("roles", schema="rbac") as batch_op:
        batch_op.create_index(batch_op.f("ix_rbac_roles_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_rbac_roles_name"), ["name"], unique=True)

    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("middle_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the record",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this record was last updated",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            comment="Soft delete flag. True means record is logically deleted",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="users",
    )
    with op.batch_alter_table("users", schema="users") as batch_op:
        batch_op.create_index(batch_op.f("ix_users_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_users_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_users_username"), ["username"], unique=True)

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False, comment="Role that has this permission"),
        sa.Column(
            "permission_id", sa.Integer(), nullable=False, comment="Permission granted to the role"
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this permission was granted to the role",
        ),
        sa.ForeignKeyConstraint(["permission_id"], ["rbac.permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["rbac.roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
        schema="rbac",
    )
    op.create_table(
        "user_permissions",
        sa.Column(
            "user_id", sa.Integer(), nullable=False, comment="User who has this direct permission"
        ),
        sa.Column(
            "permission_id",
            sa.Integer(),
            nullable=False,
            comment="Permission granted directly to the user",
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this permission was granted",
        ),
        sa.Column(
            "granted_by",
            sa.Integer(),
            nullable=True,
            comment="User ID of admin who granted this permission",
        ),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=True,
            comment="Reason for granting this direct permission (audit trail)",
        ),
        sa.ForeignKeyConstraint(["granted_by"], ["users.users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["permission_id"], ["rbac.permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "permission_id"),
        schema="rbac",
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False, comment="User who has this role"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="Role assigned to the user"),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this role was assigned",
        ),
        sa.Column(
            "assigned_by",
            sa.Integer(),
            nullable=True,
            comment="User ID of admin who assigned this role",
        ),
        sa.ForeignKeyConstraint(["assigned_by"], ["users.users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["role_id"], ["rbac.roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
        schema="rbac",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles", schema="rbac")
    op.drop_table("user_permissions", schema="rbac")
    op.drop_table("role_permissions", schema="rbac")
    with op.batch_alter_table("users", schema="users") as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_users_is_deleted"))
        batch_op.drop_index(batch_op.f("ix_users_users_email"))

    op.drop_table("users", schema="users")
    with op.batch_alter_table("roles", schema="rbac") as batch_op:
        batch_op.drop_index(batch_op.f("ix_rbac_roles_name"))
        batch_op.drop_index(batch_op.f("ix_rbac_roles_is_deleted"))

    op.drop_table("roles", schema="rbac")
    with op.batch_alter_table("permissions", schema="rbac") as batch_op:
        batch_op.drop_index(batch_op.f("ix_rbac_permissions_resource"))
        batch_op.drop_index(batch_op.f("ix_rbac_permissions_name"))
        batch_op.drop_index(batch_op.f("ix_rbac_permissions_is_deleted"))
        batch_op.drop_index("ix_permissions_resource_action")

    op.drop_table("permissions", schema="rbac")
    op.execute("DROP SCHEMA IF EXISTS rbac;")
    op.execute("DROP SCHEMA IF EXISTS users;")
    # ### end Alembic commands ###
