"""Add user table

Revision ID: b6c582ddf3ee
Revises:
Create Date: 2026-01-12 01:10:50.060142

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6c582ddf3ee"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS users")
    op.create_table(
        "user_temp",
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the record",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this record was last updated",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            comment="Soft delete flag. True means record is logically deleted",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
        schema="users",
    )
    with op.batch_alter_table("user_temp", schema="users") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_user_temp_is_deleted"), ["is_deleted"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("middle_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the record",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this record was last updated",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            comment="Soft delete flag. True means record is logically deleted",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="users",
    )
    with op.batch_alter_table("users", schema="users") as batch_op:
        batch_op.create_index(batch_op.f("ix_users_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_users_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_users_username"), ["username"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema="users") as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_users_is_deleted"))
        batch_op.drop_index(batch_op.f("ix_users_users_email"))

    op.drop_table("users", schema="users")
    with op.batch_alter_table("user_temp", schema="users") as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_user_temp_is_deleted"))

    op.drop_table("user_temp", schema="users")
    op.execute("DROP SCHEMA IF EXISTS users")
    # ### end Alembic commands ###
